# Generated by Django 4.2.4 on 2023-08-31 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=20)),
                ('cod_RFID', models.IntegerField()),
                ('descricao', models.CharField(max_length=50)),
                ('emprestada', models.BooleanField(default=False)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controleacesso.predio')),
            ],
        ),
    ]
