# Generated by Django 4.2.4 on 2023-08-31 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleacesso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chaves',
            new_name='Chave',
        ),
    ]
