# Generated by Django 4.2.4 on 2023-09-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleacesso', '0002_rename_chaves_chave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('CPF', models.IntegerField()),
                ('vinculo', models.CharField(max_length=200)),
                ('cod_RFID', models.IntegerField()),
            ],
        ),
    ]
