# Generated by Django 4.2.4 on 2023-09-21 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controleacesso', '0003_pessoas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Retirada', models.DateField()),
                ('data_Entrega', models.DateField()),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controleacesso.chave')),
                ('pessoas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controleacesso.pessoas')),
            ],
        ),
    ]
