# Generated by Django 4.2.4 on 2023-09-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleacesso', '0004_emprestimo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoas',
            new_name='Pessoa',
        ),
    ]
