# Generated by Django 4.2.4 on 2023-09-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleacesso', '0005_rename_pessoas_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='pessoas',
            new_name='pessoa',
        ),
    ]
