# Generated by Django 4.2.4 on 2023-09-21 23:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controleacesso', '0006_rename_pessoas_emprestimo_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_Entrega',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_Retirada',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 23, 17, 1, 552731, tzinfo=datetime.timezone.utc)),
        ),
    ]
