# Generated by Django 4.2.4 on 2023-09-21 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controleacesso', '0007_emprestimo_usuario_alter_emprestimo_data_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_Retirada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
