# Generated by Django 4.2.4 on 2023-09-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleacesso', '0008_alter_emprestimo_data_retirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_Entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
