# Generated by Django 4.2.4 on 2023-09-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleacesso', '0009_alter_emprestimo_data_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='usuario',
        ),
    ]
