# Generated by Django 4.2.4 on 2023-09-25 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controleacesso', '0010_remove_emprestimo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='portaria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
